class LocationData {
  // List of provinces
  static const List<String> provinces = [
    'Province 1', 
    'Province 2', 
    'Bagmati Province', 
    'Gandaki Province',
    'Lumbini Province', 
    'Karnali Province', 
    'Sudurpashchim Province'
  ];

  // Map of districts dependent on provinces
  static const Map<String, List<String>> districtMap = {
    'Province 1': ['Bhojpur', 'Dhankuta', 'Ilam', 'Jhapa', 'Khotang', 'Morang', 'Okhaldhunga', 'Panchthar', 'Sankhuwasabha', 'Solukhumbu', 'Sunsari', 'Taplejung', 'Terhathum', 'Udayapur'],
    'Province 2': ['Bara', 'Dhanusa', 'Mahottari', 'Parsa', 'Rautahat', 'Saptari', 'Sarlahi', 'Siraha'],
    'Bagmati Province': ['Bhaktapur', 'Chitwan', 'Dhading', 'Dolakha', 'Kathmandu', 'Kavrepalanchok', 'Lalitpur', 'Makwanpur', 'Nuwakot', 'Ramechhap', 'Rasuwa', 'Sindhuli', 'Sindhupalchok'],
    'Gandaki Province': ['Baglung', 'Gorkha', 'Kaski', 'Lamjung', 'Manang', 'Mustang', 'Myagdi', 'Nawalpur', 'Parbat', 'Syangja', 'Tanahun'],
    'Lumbini Province': ['Arghakhanchi', 'Banke', 'Bardiya', 'Dang', 'Gulmi', 'Kapilvastu', 'Parasi', 'Palpa', 'Pyuthan', 'Rolpa', 'Rupandehi'],
    'Karnali Province': ['Dailekh', 'Dolpa', 'Humla', 'Jajarkot', 'Jumla', 'Kalikot', 'Mugu', 'Rukum Paschim', 'Salyan', 'Surkhet'],
    'Sudurpashchim Province': ['Achham', 'Baitadi', 'Bajhang', 'Bajura', 'Dadeldhura', 'Darchula', 'Doti', 'Kailali', 'Kanchanpur'],
  };

  // Map of local governments dependent on districts
  static const Map<String, List<String>> localGovernmentMap = {
    'Bhojpur': ['Bhojpur Municipality', 'Aamchok Rural Municipality', 'Arun Rural Municipality'],
    'Dhankuta': ['Dhankuta Municipality', 'Chhathar Jorpati Rural Municipality'],
    'Ilam': ['Ilam Municipality', 'Deumai Municipality'],
    'Jhapa': ['Bhadrapur Municipality', 'Birtamod Municipality', 'Mechinagar Municipality'],
    'Khotang': ['Diktel Rupakot Majhuwagadhi Municipality', 'Halesi Tuwachung Municipality'],
    'Morang': ['Biratnagar Metropolitan City', 'Sundarharaicha Municipality'],
    'Okhaldhunga': ['Siddhicharan Municipality', 'Champadevi Rural Municipality'],
    'Panchthar': ['Phidim Municipality', 'Hilihang Rural Municipality'],
    'Sankhuwasabha': ['Khandbari Municipality', 'Chainpur Municipality'],
    'Solukhumbu': ['Solu Dudhkunda Municipality', 'Necha Salyan Rural Municipality'],
    'Sunsari': ['Inaruwa Municipality', 'Dharan Sub-Metropolitan City'],
    'Taplejung': ['Phungling Municipality', 'Meringden Rural Municipality'],
    'Terhathum': ['Myanglung Municipality', 'Laligurans Municipality'],
    'Udayapur': ['Triyuga Municipality', 'Katari Municipality'],
    'Bara': ['Kalaiya Sub-Metropolitan City', 'Kolhabi Municipality'],
    'Dhanusa': ['Janakpur Sub-Metropolitan City', 'Dhanusadham Municipality'],
    'Mahottari': ['Jaleshwar Municipality', 'Loharpatti Municipality'],
    'Parsa': ['Birgunj Metropolitan City', 'Pokhariya Municipality'],
    'Rautahat': ['Gaur Municipality', 'Garuda Municipality'],
    'Saptari': ['Rajbiraj Municipality', 'Hanumannagar Kankalini Municipality'],
    'Sarlahi': ['Malangawa Municipality', 'Ishworpur Municipality'],
    'Siraha': ['Lahan Municipality', 'Siraha Municipality'],
    'Bhaktapur': ['Bhaktapur Municipality', 'Madhyapur Thimi Municipality'],
    'Chitwan': ['Bharatpur Metropolitan City', 'Kalika Municipality'],
    'Dhading': ['Nilkantha Municipality', 'Gajuri Rural Municipality'],
    'Dolakha': ['Bhimeshwar Municipality', 'Jiri Municipality'],
    'Kathmandu': ['Kathmandu Metropolitan City', 'Kirtipur Municipality'],
    'Kavrepalanchok': ['Dhulikhel Municipality', 'Panauti Municipality'],
    'Lalitpur': ['Lalitpur Metropolitan City', 'Godawari Municipality'],
    'Makwanpur': ['Hetauda Sub-Metropolitan City', 'Thaha Municipality'],
    'Nuwakot': ['Bidur Municipality', 'Belkotgadhi Municipality'],
    'Ramechhap': ['Manthali Municipality', 'Ramechhap Municipality'],
    'Rasuwa': ['Dhunche Municipality', 'Gosaikunda Rural Municipality'],
    'Sindhuli': ['Kamalamai Municipality', 'Dudhauli Municipality'],
    'Sindhupalchok': ['Chautara Sangachokgadhi Municipality', 'Melamchi Municipality'],
    'Baglung': ['Baglung Municipality', 'Galkot Municipality'],
    'Gorkha': ['Gorkha Municipality', 'Palungtar Municipality'],
    'Kaski': ['Pokhara Metropolitan City', 'Annapurna Rural Municipality'],
    'Lamjung': ['Besisahar Municipality', 'Madhya Nepal Municipality'],
    'Manang': ['Chame Rural Municipality', 'Narpa Bhumi Rural Municipality'],
    'Mustang': ['Gharpajhong Rural Municipality', 'Lomanthang Rural Municipality'],
    'Myagdi': ['Beni Municipality', 'Raghuganga Rural Municipality'],
    'Nawalpur': ['Gaindakot Municipality', 'Kawasoti Municipality'],
    'Parbat': ['Kusma Municipality', 'Phalewas Municipality'],
    'Syangja': ['Putalibazar Municipality', 'Waling Municipality'],
    'Tanahun': ['Byas Municipality', 'Bhanu Municipality'],
    'Arghakhanchi': ['Sandhikharka Municipality', 'Sitganga Municipality'],
    'Banke': ['Nepalgunj Sub-Metropolitan City', 'Kohalpur Municipality'],
    'Bardiya': ['Gulariya Municipality', 'Rajapur Municipality'],
    'Dang': ['Ghorahi Sub-Metropolitan City', 'Tulsipur Sub-Metropolitan City'],
    'Gulmi': ['Resunga Municipality', 'Musikot Municipality'],
    'Kapilvastu': ['Kapilvastu Municipality', 'Banganga Municipality'],
    'Parasi': ['Ramgram Municipality', 'Bardaghat Municipality'],
    'Palpa': ['Tansen Municipality', 'Rampur Municipality'],
    'Pyuthan': ['Pyuthan Municipality', 'Swargadwari Municipality'],
    'Rolpa': ['Rolpa Municipality', 'Thawang Rural Municipality'],
    'Rupandehi': ['Butwal Sub-Metropolitan City', 'Siddharthanagar Municipality'],
    'Dailekh': ['Narayan Municipality', 'Dullu Municipality'],
    'Dolpa': ['Dunai Municipality', 'Shey Phoksundo Rural Municipality'],
    'Humla': ['Simikot Rural Municipality', 'Namkha Rural Municipality'],
    'Jajarkot': ['Khalanga Municipality', 'Barekot Rural Municipality'],
    'Jumla': ['Chandannath Municipality', 'Tatopani Rural Municipality'],
    'Kalikot': ['Manma Municipality', 'Raskot Municipality'],
    'Mugu': ['Gamgadhi Rural Municipality', 'Chhayanath Rara Municipality'],
    'Rukum Paschim': ['Musikot Municipality', 'Chaurjahari Municipality'],
    'Salyan': ['Sharada Municipality', 'Bagchaur Municipality'],
    'Surkhet': ['Birendranagar Municipality', 'Gurbhakot Municipality'],
    'Achham': ['Mangalsen Municipality', 'Sanphebagar Municipality'],
    'Baitadi': ['Dasharathchanda Municipality', 'Patan Municipality'],
    'Bajhang': ['Jayaprithvi Municipality', 'Chhabispathibhera Rural Municipality'],
    'Bajura': ['Martadi Municipality', 'Budhinanda Municipality'],
    'Dadeldhura': ['Amargadhi Municipality', 'Parashuram Municipality'],
    'Darchula': ['Mahakali Municipality', 'Shailyashikhar Municipality'],
    'Doti': ['Dipayal Silgadhi Municipality', 'Shikhar Municipality'],
    'Kailali': ['Dhangadhi Sub-Metropolitan City', 'Tikapur Municipality'],
    'Kanchanpur': ['Bhimdatta Municipality', 'Mahakali Municipality'],
  };
}
