// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtU-2RGfB0NtSh6MXvmQ2taptC34XazFg',
    appId: '1:372617062510:web:7dc12c513cd9ba47265e7f',
    messagingSenderId: '372617062510',
    projectId: 'blood-donation-app-57be3',
    authDomain: 'blood-donation-app-57be3.firebaseapp.com',
    storageBucket: 'blood-donation-app-57be3.appspot.com',
    measurementId: 'G-4JQXCNEMDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7HKTYLAYLS2e_65oIIshfyTM_YdhWhSY',
    appId: '1:372617062510:android:f0e9a33e695b287a265e7f',
    messagingSenderId: '372617062510',
    projectId: 'blood-donation-app-57be3',
    storageBucket: 'blood-donation-app-57be3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuRANjWjjWZecMUzJ7IUl6AQpZgvkMHBw',
    appId: '1:372617062510:ios:6343b7911037eec9265e7f',
    messagingSenderId: '372617062510',
    projectId: 'blood-donation-app-57be3',
    storageBucket: 'blood-donation-app-57be3.appspot.com',
    iosBundleId: 'com.example.bloodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuRANjWjjWZecMUzJ7IUl6AQpZgvkMHBw',
    appId: '1:372617062510:ios:6343b7911037eec9265e7f',
    messagingSenderId: '372617062510',
    projectId: 'blood-donation-app-57be3',
    storageBucket: 'blood-donation-app-57be3.appspot.com',
    iosBundleId: 'com.example.bloodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtU-2RGfB0NtSh6MXvmQ2taptC34XazFg',
    appId: '1:372617062510:web:605999833b7a9bbc265e7f',
    messagingSenderId: '372617062510',
    projectId: 'blood-donation-app-57be3',
    authDomain: 'blood-donation-app-57be3.firebaseapp.com',
    storageBucket: 'blood-donation-app-57be3.appspot.com',
    measurementId: 'G-EXJJQXMJZ0',
  );
}
